# Generated by Django 4.1 on 2022-09-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFami', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='familiar_2',
        ),
        migrations.DeleteModel(
            name='familiar_3',
        ),
    ]
