# Generated by Django 4.1 on 2022-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFami', '0002_delete_familiar_2_delete_familiar_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='familiar_1',
        ),
    ]
